=== magnus-i-p-j/zombie.js/js/common/rulebook/concept.schema.json
{
  "type":"object",
  "$schema":"http://json-schema.org/draft-03/schema",
  "id":"#",
  "required":true,
  "properties":{
    "asset":{
      "type":"array",
      "id":"asset",
      "required":true,
      "items":{
        "type":"object",
        "id":"0",
        "required":true,
        "properties":{
          "description":{
            "type":"string",
            "id":"description",
            "required":true
          },
          "name":{
            "type":"string",
            "id":"name",
            "required":true
          },
          "type":{
            "type":"string",
            "id":"type",
            "required":true
          }
        }
      }

    },
    "improvement":{
      "type":"array",
      "id":"improvement",
      "required":true,
      "items":[
        {
          "type":"object",
          "id":"0",
          "required":true,
          "properties":{
            "cost":{
              "type":"object",
              "id":"cost",
              "required":true,
              "properties":{
                "min_turns":{
                  "type":"number",
                  "id":"min_turns",
                  "required":true
                }
              }
            },
            "description":{
              "type":"string",
              "id":"description",
              "required":true
            },
            "effect":{
              "type":"object",
              "id":"effect",
              "required":true,
              "properties":{
                "terrain":{
                  "type":"string",
                  "id":"terrain",
                  "required":true
                }
              }
            },
            "name":{
              "type":"string",
              "id":"name",
              "required":true
            },
            "prerequisites":{
              "type":"object",
              "id":"prerequisites",
              "required":true,
              "properties":{
                "terrain":{
                  "type":"array",
                  "id":"terrain",
                  "required":true,
                  "items":{
                    "type":"string",
                    "id":"0",
                    "required":true
                  }

                }
              }
            },
            "type":{
              "type":"string",
              "id":"type",
              "required":true
            }
          }
        },
        {
          "type":"object",
          "id":"1",
          "required":true,
          "properties":{
            "cost":{
              "type":"object",
              "id":"cost",
              "required":true,
              "properties":{
                "skill":{
                  "type":"object",
                  "id":"skill",
                  "required":true,
                  "properties":{
                    "building":{
                      "type":"number",
                      "id":"building",
                      "required":true
                    },
                    "zlaying":{
                      "type":"number",
                      "id":"zlaying",
                      "required":true
                    }
                  }
                }
              }
            },
            "description":{
              "type":"string",
              "id":"description",
              "required":true
            },
            "effect":{
              "type":"object",
              "id":"effect",
              "required":true,
              "properties":{
                "terrain":{
                  "type":"string",
                  "id":"terrain",
                  "required":true
                }
              }
            },
            "name":{
              "type":"string",
              "id":"name",
              "required":true
            },
            "prerequisites":{
              "type":"object",
              "id":"prerequisites",
              "required":true,
              "properties":{
                "terrain":{
                  "type":"array",
                  "id":"terrain",
                  "required":true,
                  "items":{
                    "type":"string",
                    "id":"0",
                    "required":true
                  }

                }
              }
            },
            "type":{
              "type":"string",
              "id":"type",
              "required":true
            }
          }
        },
        {
          "type":"object",
          "id":"2",
          "required":true,
          "properties":{
            "cost":{
              "type":"object",
              "id":"cost",
              "required":true,
              "properties":{
                "skill":{
                  "type":"object",
                  "id":"skill",
                  "required":true,
                  "properties":{
                    "farming":{
                      "type":"number",
                      "id":"farming",
                      "required":true
                    }
                  }
                }
              }
            },
            "description":{
              "type":"string",
              "id":"description",
              "required":true
            },
            "effect":{
              "type":"object",
              "id":"effect",
              "required":true,
              "properties":{
                "improvement":{
                  "type":"string",
                  "id":"improvement",
                  "required":true
                }
              }
            },
            "name":{
              "type":"string",
              "id":"name",
              "required":true
            },
            "prerequisites":{
              "type":"object",
              "id":"prerequisites",
              "required":true,
              "properties":{
                "terrain":{
                  "type":"array",
                  "id":"terrain",
                  "required":true,
                  "items":{
                    "type":"string",
                    "id":"0",
                    "required":true
                  }

                }
              }
            },
            "type":{
              "type":"string",
              "id":"type",
              "required":true
            }
          }
        },
        {
          "type":"object",
          "id":"3",
          "required":true,
          "properties":{
            "cost":{
              "type":"object",
              "id":"cost",
              "required":true,
              "properties":{
                "min_turns":{
                  "type":"number",
                  "id":"min_turns",
                  "required":true
                },
                "skill":{
                  "type":"object",
                  "id":"skill",
                  "required":true,
                  "properties":{
                    "farming":{
                      "type":"number",
                      "id":"farming",
                      "required":true
                    }
                  }
                }
              }
            },
            "description":{
              "type":"string",
              "id":"description",
              "required":true
            },
            "effect":{
              "type":"object",
              "id":"effect",
              "required":true,
              "properties":{
                "improvement":{
                  "type":"string",
                  "id":"improvement",
                  "required":true
                }
              }
            },
            "name":{
              "type":"string",
              "id":"name",
              "required":true
            },
            "prerequisites":{
              "type":"object",
              "id":"prerequisites",
              "required":true,
              "properties":{
                "blocked":{
                  "type":"boolean",
                  "id":"blocked",
                  "required":true
                }
              }
            },
            "type":{
              "type":"string",
              "id":"type",
              "required":true
            }
          }
        },
        {
          "type":"object",
          "id":"4",
          "required":true,
          "properties":{
            "cost":{
              "type":"object",
              "id":"cost",
              "required":true,
              "properties":{
                "max_turns":{
                  "type":"number",
                  "id":"max_turns",
                  "required":true
                },
                "skill":{
                  "type":"object",
                  "id":"skill",
                  "required":true,
                  "properties":{
                    "farming":{
                      "type":"number",
                      "id":"farming",
                      "required":true
                    }
                  }
                }
              }
            },
            "description":{
              "type":"string",
              "id":"description",
              "required":true
            },
            "effect":{
              "type":"object",
              "id":"effect",
              "required":true,
              "properties":{
                "assets":{
                  "type":"object",
                  "id":"assets",
                  "required":true,
                  "properties":{
                    "comment":{
                      "type":"string",
                      "id":"comment",
                      "required":true
                    },
                    "food":{
                      "type":"number",
                      "id":"food",
                      "required":true
                    }
                  }
                }
              }
            },
            "name":{
              "type":"string",
              "id":"name",
              "required":true
            },
            "prerequisites":{
              "type":"object",
              "id":"prerequisites",
              "required":true,
              "properties":{
                "blocked":{
                  "type":"boolean",
                  "id":"blocked",
                  "required":true
                }
              }
            },
            "type":{
              "type":"string",
              "id":"type",
              "required":true
            }
          }
        }
      ]
    },
    "skills":{
      "type":"array",
      "id":"skills",
      "required":true,
      "items":{
        "type":"object",
        "id":"0",
        "required":true,
        "properties":{
          "description":{
            "type":"string",
            "id":"description",
            "required":true
          },
          "model":{
            "type":"string",
            "id":"model",
            "required":true
          },
          "name":{
            "type":"string",
            "id":"name",
            "required":true
          },
          "type":{
            "type":"string",
            "id":"type",
            "required":true
          }
        }
      }

    },
    "terrain":{
      "type":"array",
      "id":"terrain",
      "required":true,
      "items":{
        "type":"object",
        "id":"0",
        "required":true,
        "properties":{
          "description":{
            "type":"string",
            "id":"description",
            "required":true
          },
          "name":{
            "type":"string",
            "id":"name",
            "required":true
          },
          "type":{
            "type":"string",
            "id":"type",
            "required":true
          }
        }
      }

    }
  }
}

=== magnus-i-p-j/zombie.js/js/common/rulebook/ruleset.json
{
  "improvement":[
    {
      "type":"look_at_area",
      "name":"Look at area",
      "description":"Look at stuff.",
      "prerequisites":{
        "terrain":["grass"]
      },
      "cost":{
        "min_turns":5
      },
      "effect":{
        "terrain":"watched_grass"
      }
    },
    {
      "type":"secure_area",
      "name":"Secure area",
      "description":"Build a zombie-proofish fence around a tile and kill all zombies within.",
      "prerequisites":{
        "terrain":["grass"]
      },
      "cost":{
        "skill":{
          "zlaying":100,
          "building":100
        }
      },
      "effect":{
        "terrain":"fenced_grass"
      }
    },
    {
      "type":"field_plant",
      "name":"Plant field",
      "description":"Plow a patch of land and plant some beets.",
      "prerequisites":{
        "terrain":["field"]
      },
      "cost":{
        "skill":{
          "farming":100
        }
      },
      "effect":{
        "improvement":"field_tend"
      }
    },
    {
      "type":"field_tend",
      "name":"Tend field",
      "description":"Tend a patch of land and weed some beets.",
      "prerequisites":{
        "blocked":true
      },
      "cost":{
        "skill":{
          "farming":10
        },
        "min_turns":5
      },
      "effect":{
        "improvement":"field_harvest"
      }
    },
    {
      "type":"field_harvest",
      "name":"Harvest field",
      "description":"Harvest a patch of land and get some beets.",
      "prerequisites":{
        "blocked":true
      },
      "cost":{
        "skill":{
          "farming":100
        },
        "max_turns":2
      },
      "effect":{
        "assets":{
          "food":300,
          "comment":"We'll need to figure out the details later."
        }
      }
    }
  ],
  "terrain":[
    {
      "type":"field",
      "name":"Field",
      "description":"A patch of land where some beets are growing."
    },
    {
      "type":"fenced_grass",
      "name":"Fenced grass",
      "description":"A patch of land surrounded by wicked looking barbed wire fence. Some zombie bits are stuck in it"
    },
    {
      "type":"grass",
      "name":"Grass",
      "description":"A patch of green grass, untouched by the zombie apocalypse."
    },
    {
      "type":"water",
      "name":"Water",
      "description":"A patch of blue water, untouched by the zombie apocalypse."
    },
    {
      "type":"hills",
      "name":"Hills",
      "description":"A patch of high hill, untouched by the zombie apocalypse."
    }
  ],
  "asset":[
    {
      "type":"food",
      "name":"Food",
      "description":"Some generic post-apocalyptic food. The taste is indescribable (because there isn't any) and the contents is mostly beets."
    }
  ],
  "skills":[
    {
      "type":"zlaying",
      "name":"Et cetera",
      "description":"et cetera",
      "model":"linear"
    }
  ]
}
